---
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    ports:
      - "3389:3000"
    environment:
      DATABASE_URL: postgresql://postgres:rj336699@45.144.225.49:5432/umami
      DATABASE_TYPE: postgresql
      APP_SECRET: replace-me-with-a-random-string
    init: true
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:3000/api/heartbeat"]
      interval: 5s
      timeout: 5s
      retries: 5
